version: '3.5'
services:
  geth:
    image: ethereum/client-go
    container_name: ethereum-node
    hostname: ethereum-node
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8545:8545"
      - "30303:30303"
    command: ["ethereum/client-go", "--fast", "--cache=512"]
